-- 프로그래머스, 서울에 위치한 식당 목록 출력하기
-- LV4
-- 조인, 서브쿼리, 그룹핑, 2가지 기준으로 정렬, 평균 함수, 반올림 함수
SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM (SELECT V.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, V.REVIEW_SCORE
      FROM REST_INFO I
               INNER JOIN REST_REVIEW V
                          ON I.REST_ID = V.REST_ID
      WHERE I.ADDRESS LIKE '서울%') R -- '%서울%' 하지않도록 주의
GROUP BY  R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS
ORDER BY SCORE DESC, R.FAVORITES DESC;