-- SKILLCODES, DEVELOPERS
-- 비트 조인; 오라클 BITAND, mysql & 연산
SELECT DISTINCT T1.ID, T1.EMAIL, T1.FIRST_NAME, T1.LAST_NAME
FROM DEVELOPERS T1
         INNER JOIN SKILLCODES T2
                    ON (T1.SKILL_CODE & T2.CODE) != 0
WHERE T2.CATEGORY = 'Front End'
ORDER BY T1.ID;